# Generated by Django 3.0.5 on 2020-05-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ref', models.DateField()),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('cliente', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='test1/')),
            ],
        ),
    ]
