# Generated by Django 3.0.5 on 2020-05-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_auto_20200513_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cliente',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(max_length=70),
        ),
    ]
