# Generated by Django 3.0.6 on 2020-05-21 02:41

import Proyectos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_auto_20200517_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='img',
        ),
        migrations.CreateModel(
            name='Images_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=Proyectos.models.content_file_name)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.Obra')),
            ],
        ),
    ]
