# Generated by Django 3.0.5 on 2020-05-21 17:53

import Proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0005_obra_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cover_img',
            field=models.FileField(upload_to=Proyectos.models.content_cover_name),
        ),
    ]
